name: unihr
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'





dependencies:
  gradient_borders: ^1.0.0
  table_calendar: ^3.0.9
  carousel_slider: ^4.2.1
  http: ^1.1.0
  circular_bottom_navigation: ^2.3.0
  drop_shadow_image: ^0.9.1
  like_button: ^2.0.5
  flutter_polls: ^0.1.2
  icon_decoration: ^2.0.2
  flutter_dotenv: ^5.1.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  confetti: ^0.7.0
  google_fonts: ^5.1.0
  responsive_builder: ^0.7.0
  dartz: ^0.10.1
  responsive_framework: ^1.1.0
  provider: ^6.0.5
  shimmer: ^3.0.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^8.0.0
  loading_animation_widget: ^1.2.0+4
  get_it: ^7.6.0
  flutter_typeahead: ^4.6.2
  awesome_notifications: ^0.7.4+1
  flutter_local_notifications: ^15.1.1
  flutter_launcher_icons: ^0.13.1
  logger: ^2.0.2



  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  remove_alpha_ios: true
  image_path: "assets/logoUni.png"


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/shinosukeedit.jpg
